export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGRENIENTS_FAILED = 'FETCH_INGRENIENTS_FAILED';

export const PURCHASE_BURGER_SUCCES = 'PURCHASE_BURGER_SUCCES';
export const PUTCHASE_BURGER_FAIL = 'PUTCHASE_BURGER_FAIL';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';